<?php

/**
 * @file
 * Contains user_points.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_points_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_points module.
    case 'help.page.user_points':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User points module provides api functions for storing and removing points.') . '</p>';
      return $output;

    default:
  }
}
